[package]
name = "rinha-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
time = {version = "0.3.36", features = ["macros"]}
tokio = {version = "1.40.0", features = ["full"]}
uuid = {version = "1.10.0", features = ["v7"]}
